version: "3.9"
   
services:
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    <<: &web
      build: .
      environment:
        - DATABASE_URL=postgres://postgres:postgres@db/postgres
        - VIRTUAL_HOST=apiproject.localhost
      depends_on:
        - db
      volumes:
        - .:/code/
      ports:
        - "8000:8000"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  db-data: